version: '3'
services:
  backend:
    build: ./backend/
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - DB_URL=jdbc:postgresql://database:5432/mydb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    env_file:
      - smtp_credentials.env
    networks:
      - db-network

  frontend:
    build: ./frontend/webshop-web/
    ports:
      - 5173:5173
    depends_on:
      - backend

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

